-- Stocks V2 / Market Signal Deck schema entry point.
--
-- Apply the production Supabase migrations instead of this legacy starter path:
--
--   supabase/migrations/20260613153000_market_platform_schema.sql
--   supabase/migrations/20260613154000_cron_setup.sql
--
-- Seed glossary terms with:
--
--   supabase/seed/glossary_terms.sql
