insert into public.glossary_terms
  (term, short_definition, full_definition, beginner_example, formula, related_terms, category)
values
  ('Volatility', 'How much an asset moves up and down.', 'Volatility measures how widely returns vary over time. Higher volatility can mean larger gains or losses and wider prediction ranges.', 'A stock that often moves 5% in a day is more volatile than one that usually moves 0.5%.', null, array['ATR', 'Risk'], 'risk'),
  ('Market capitalization', 'The total market value of a company or asset.', 'For stocks, market cap is share price multiplied by shares outstanding. Crypto market cap is price multiplied by circulating supply.', 'A company with 1 billion shares at $50 has a $50 billion market cap.', 'price * shares_outstanding', array['Liquidity', 'Large cap'], 'fundamentals'),
  ('RSI', 'A momentum indicator that compares recent gains and losses.', 'Relative Strength Index ranges from 0 to 100. Readings above 70 may indicate overbought conditions, while readings below 30 may indicate oversold conditions.', 'RSI does not guarantee reversal; it is one input in a broader signal.', '100 - 100 / (1 + average_gain / average_loss)', array['Momentum', 'Overbought'], 'technical'),
  ('MACD', 'A trend-momentum indicator built from moving averages.', 'MACD compares a fast EMA and slow EMA. The histogram shows whether momentum is improving or weakening.', 'A positive MACD histogram can support a bullish signal, but it can lag rapid moves.', 'EMA(12) - EMA(26)', array['EMA', 'Momentum'], 'technical'),
  ('Volume', 'How many shares, contracts, or coins traded.', 'Volume shows participation. High relative volume can confirm unusual interest or risk.', 'A price move on low volume may be less reliable than one with strong volume.', null, array['Relative volume', 'Liquidity'], 'market-data'),
  ('Liquidity', 'How easily an asset can be bought or sold.', 'Liquid markets usually have more participants, tighter spreads, and lower slippage. Illiquid assets can move sharply.', 'SPY is usually more liquid than a small thinly traded stock.', null, array['Spread', 'Volume'], 'market-data'),
  ('Support', 'A price area where buyers recently appeared.', 'Support is not a floor. It is an observed zone where demand previously slowed a decline.', 'If a stock bounced near $50 several times, $50 may be watched as support.', null, array['Resistance', 'Risk'], 'technical'),
  ('Resistance', 'A price area where sellers recently appeared.', 'Resistance is not a ceiling. It is an observed zone where supply previously slowed an advance.', 'If a stock failed near $100 repeatedly, traders may watch $100 as resistance.', null, array['Support', 'Breakout'], 'technical'),
  ('Bullish', 'Expecting or favoring upward movement.', 'A bullish signal means measured inputs lean upward for the selected horizon, not that gains are guaranteed.', 'A bullish 14-day signal can still be wrong if news or market conditions change.', null, array['Bearish', 'Confidence'], 'signals'),
  ('Bearish', 'Expecting or favoring downward movement.', 'A bearish signal means measured inputs lean downward for the selected horizon, not that losses are guaranteed.', 'A bearish signal may be useful for risk review even if the price later rises.', null, array['Bullish', 'Risk'], 'signals'),
  ('Moving average', 'The average price over a selected period.', 'Moving averages smooth price action. Shorter averages react faster; longer averages represent broader trend.', 'SMA 20 follows recent price more closely than SMA 200.', 'sum(close, n) / n', array['SMA', 'EMA'], 'technical'),
  ('Sentiment', 'A measure of whether related news or discussion is positive, neutral, or negative.', 'Sentiment can explain attention and risk, but it does not guarantee price direction.', 'Positive headlines can still appear before a price falls.', null, array['News', 'Relevance'], 'news'),
  ('Spread', 'The difference between bid and ask.', 'A wider spread can make trading more expensive and signal lower liquidity.', 'If bid is $10.00 and ask is $10.10, the spread is $0.10.', 'ask - bid', array['Bid', 'Ask', 'Liquidity'], 'market-data'),
  ('Momentum', 'The strength and speed of recent price movement.', 'Momentum indicators look at whether an asset is accelerating upward or downward.', 'Strong momentum can persist, but it can also reverse suddenly.', null, array['RSI', 'MACD'], 'technical'),
  ('Diversification', 'Spreading risk across different assets.', 'Diversification can reduce concentration risk, but it cannot eliminate market risk.', 'Owning only one volatile stock is usually more concentrated than owning a broad ETF.', null, array['Risk', 'ETF'], 'risk'),
  ('Dividend', 'A cash payment from a company to shareholders.', 'Dividends may provide income but can change or be suspended.', 'A company may pay a quarterly dividend, but the stock price can still fall.', null, array['Yield', 'Fundamentals'], 'fundamentals'),
  ('ETF', 'A fund traded on an exchange like a stock.', 'Exchange-traded funds can hold baskets of stocks, bonds, commodities, or other assets.', 'SPY is an ETF that tracks the S&P 500.', null, array['Index', 'Diversification'], 'assets'),
  ('Index', 'A benchmark representing a group of assets.', 'Indexes track baskets of securities and are often used to measure broad market performance.', 'The S&P 500 is an index of large U.S. companies.', null, array['ETF', 'Market breadth'], 'assets'),
  ('Short selling', 'Borrowing and selling an asset hoping to buy it back lower.', 'Short selling can lose more than the initial amount if the price rises sharply.', 'Shorting a stock at $50 is risky if it rises to $100.', null, array['Risk', 'Bearish'], 'risk'),
  ('Risk', 'The possibility of loss or unwanted outcome.', 'Risk includes price volatility, liquidity, data quality, news, concentration, and model uncertainty.', 'A high-confidence prediction can still have high risk.', null, array['Volatility', 'Confidence'], 'risk')
on conflict (term) do update set
  short_definition = excluded.short_definition,
  full_definition = excluded.full_definition,
  beginner_example = excluded.beginner_example,
  formula = excluded.formula,
  related_terms = excluded.related_terms,
  category = excluded.category;
